### ISSUE TITLE
No license for the code?

### ISSUE THREAD

**Issue by daeldir** [mhagiwara/camxes.js#2]
Your code is used [here](https://github.com/Ilmen-vodhr/ilmentufa). While contributing to this project, I remarked that it had no license. On the [issue I opened](https://github.com/Ilmen-vodhr/ilmentufa/issues/27), I've been answered:

> we need to look at the initial camxes.js website to see what Masato wrote there.

You didn't write anything :-)

While [Github Terms of Service](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership) allow us to use your code (which basic copyright doesn't, in many countries), it is always better to specifically know what the author really wants. 

As it is, you are not even cited as the original author (a quick way to not have this problem is to put the copyright notice in the header of the source code).

I invite you to create a “COPYING” or a “LICENSE” file, with whatever license you want in it. Github made [this site](http://choosealicense.com/) if you don't know what to choose.

Thanks for your attention, and your code :-)

**Comment by mhagiwara** [comment]
Thank you for pointing this out! I added LICENSE (MIT License) and updated the files.
